// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/webhook/webhook.proto

package webhook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// JSON string of data
	Data                 string               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=creation_time,proto3" json:"creation_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhook_4f5906761001d48d, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Event) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

type Webhook struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventTypes           []string             `protobuf:"bytes,2,rep,name=event_types,proto3" json:"event_types,omitempty"`
	Enabled              bool                 `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Secret               string               `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Uri                  string               `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=creation_time,proto3" json:"creation_time,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_time,json=update_time,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Webhook) Reset()         { *m = Webhook{} }
func (m *Webhook) String() string { return proto.CompactTextString(m) }
func (*Webhook) ProtoMessage()    {}
func (*Webhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhook_4f5906761001d48d, []int{1}
}
func (m *Webhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Webhook.Unmarshal(m, b)
}
func (m *Webhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Webhook.Marshal(b, m, deterministic)
}
func (dst *Webhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Webhook.Merge(dst, src)
}
func (m *Webhook) XXX_Size() int {
	return xxx_messageInfo_Webhook.Size(m)
}
func (m *Webhook) XXX_DiscardUnknown() {
	xxx_messageInfo_Webhook.DiscardUnknown(m)
}

var xxx_messageInfo_Webhook proto.InternalMessageInfo

func (m *Webhook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Webhook) GetEventTypes() []string {
	if m != nil {
		return m.EventTypes
	}
	return nil
}

func (m *Webhook) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Webhook) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Webhook) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Webhook) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *Webhook) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "webhook.Event")
	proto.RegisterType((*Webhook)(nil), "webhook.Webhook")
}

func init() {
	proto.RegisterFile("pkg/api/webhook/webhook.proto", fileDescriptor_webhook_4f5906761001d48d)
}

var fileDescriptor_webhook_4f5906761001d48d = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0xba, 0xdb, 0xda, 0xa9, 0x8a, 0xe4, 0x20, 0x61, 0x41, 0x2c, 0x7b, 0xea, 0xa9,
	0x05, 0x3d, 0x0b, 0x5e, 0xfc, 0x03, 0x41, 0xf0, 0xb8, 0xa4, 0x9b, 0xb1, 0x86, 0xdd, 0x6d, 0x42,
	0x9b, 0x2a, 0xde, 0xf4, 0x9f, 0x4b, 0x92, 0x2d, 0x28, 0x3d, 0xc8, 0x9e, 0x32, 0xf3, 0xf1, 0xf2,
	0xde, 0x1b, 0xb8, 0x31, 0xbb, 0xb6, 0x16, 0x46, 0xd5, 0x1f, 0xd8, 0xbc, 0x69, 0xbd, 0x9b, 0xde,
	0xca, 0xf4, 0xda, 0x6a, 0x9a, 0x1e, 0xd7, 0xd5, 0x6d, 0xab, 0x75, 0xbb, 0xc7, 0xda, 0xe3, 0x66,
	0x7c, 0xad, 0xad, 0x3a, 0xe0, 0x60, 0xc5, 0xc1, 0x04, 0xe5, 0xfa, 0x3b, 0x82, 0xe5, 0xd3, 0x3b,
	0x76, 0x96, 0x5e, 0x02, 0x51, 0x92, 0x45, 0x45, 0x54, 0x66, 0x9c, 0x28, 0x49, 0x29, 0x2c, 0xec,
	0xa7, 0x41, 0x46, 0x3c, 0xf1, 0xb3, 0x63, 0x52, 0x58, 0xc1, 0xe2, 0xc0, 0xdc, 0x4c, 0x1f, 0xe1,
	0x62, 0xdb, 0xa3, 0xb0, 0x4a, 0x77, 0x1b, 0xe7, 0xce, 0x16, 0x45, 0x54, 0xe6, 0x77, 0xab, 0x2a,
	0x44, 0x57, 0x53, 0x74, 0xf5, 0x3c, 0x45, 0xf3, 0xbf, 0x1f, 0xd6, 0x5f, 0x04, 0xd2, 0x97, 0x50,
	0x78, 0xd6, 0xa2, 0x80, 0x1c, 0x5d, 0xbd, 0x8d, 0xcb, 0x1f, 0x18, 0x29, 0xe2, 0x32, 0xe3, 0xbf,
	0x11, 0x65, 0x90, 0x62, 0x27, 0x9a, 0x3d, 0x4a, 0x5f, 0xeb, 0x8c, 0x4f, 0x2b, 0xbd, 0x86, 0x64,
	0xc0, 0x6d, 0x8f, 0xd6, 0x57, 0xca, 0xf8, 0x71, 0xa3, 0x57, 0x10, 0x8f, 0xbd, 0x62, 0x4b, 0x0f,
	0xdd, 0x38, 0xbf, 0x21, 0x39, 0xf1, 0x06, 0xfa, 0x00, 0xe7, 0xa3, 0x91, 0xc2, 0xa2, 0x0c, 0x06,
	0xe9, 0xbf, 0x06, 0x79, 0xd0, 0x7b, 0x79, 0x93, 0x78, 0xc1, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0xc8, 0x90, 0x7b, 0xd8, 0x01, 0x00, 0x00,
}
