// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/webhook/webhook.proto

package webhook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=creation_time,proto3" json:"creation_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhook_4540c1010ab24c99, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

type Webhook struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventTypes           []string             `protobuf:"bytes,2,rep,name=event_types,proto3" json:"event_types,omitempty"`
	Enabled              bool                 `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Secret               string               `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Uri                  string               `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=creation_time,proto3" json:"creation_time,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_time,json=update_time,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Webhook) Reset()         { *m = Webhook{} }
func (m *Webhook) String() string { return proto.CompactTextString(m) }
func (*Webhook) ProtoMessage()    {}
func (*Webhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhook_4540c1010ab24c99, []int{1}
}
func (m *Webhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Webhook.Unmarshal(m, b)
}
func (m *Webhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Webhook.Marshal(b, m, deterministic)
}
func (dst *Webhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Webhook.Merge(dst, src)
}
func (m *Webhook) XXX_Size() int {
	return xxx_messageInfo_Webhook.Size(m)
}
func (m *Webhook) XXX_DiscardUnknown() {
	xxx_messageInfo_Webhook.DiscardUnknown(m)
}

var xxx_messageInfo_Webhook proto.InternalMessageInfo

func (m *Webhook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Webhook) GetEventTypes() []string {
	if m != nil {
		return m.EventTypes
	}
	return nil
}

func (m *Webhook) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Webhook) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Webhook) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Webhook) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

func (m *Webhook) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "webhook.Event")
	proto.RegisterType((*Webhook)(nil), "webhook.Webhook")
}

func init() {
	proto.RegisterFile("pkg/api/webhook/webhook.proto", fileDescriptor_webhook_4540c1010ab24c99)
}

var fileDescriptor_webhook_4540c1010ab24c99 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x4f, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0xa5, 0xd9, 0xd6, 0xda, 0xaf, 0x53, 0x24, 0x07, 0x09, 0x03, 0x31, 0xec, 0xd4, 0x53, 0x0b,
	0x7a, 0x16, 0xbc, 0xf8, 0x07, 0x82, 0xe0, 0x71, 0xa4, 0xcb, 0x67, 0x0d, 0xdb, 0x9a, 0xd0, 0xa6,
	0x8a, 0x37, 0xfd, 0xe7, 0x92, 0x64, 0x05, 0x65, 0x07, 0xf1, 0x94, 0xf7, 0x1e, 0x2f, 0xef, 0xbd,
	0x0f, 0xae, 0xed, 0xae, 0xad, 0xa5, 0xd5, 0xf5, 0x3b, 0x36, 0xaf, 0xc6, 0xec, 0xa6, 0xb7, 0xb2,
	0xbd, 0x71, 0x86, 0x66, 0x47, 0xba, 0xba, 0x69, 0x8d, 0x69, 0xf7, 0x58, 0x07, 0xb9, 0x19, 0x5f,
	0x6a, 0xa7, 0x0f, 0x38, 0x38, 0x79, 0xb0, 0xd1, 0xb9, 0xfe, 0x4a, 0x60, 0xf1, 0xf8, 0x86, 0x9d,
	0xa3, 0x17, 0x40, 0xb4, 0x62, 0x09, 0x4f, 0xca, 0x5c, 0x10, 0xad, 0x28, 0x85, 0xb9, 0xfb, 0xb0,
	0xc8, 0x48, 0x50, 0x02, 0xf6, 0x9a, 0x92, 0x4e, 0xb2, 0x19, 0x4f, 0xca, 0xa5, 0x08, 0x98, 0x3e,
	0xc0, 0xf9, 0xb6, 0x47, 0xe9, 0xb4, 0xe9, 0x36, 0x3e, 0x9d, 0xcd, 0x79, 0x52, 0x16, 0xb7, 0xab,
	0x2a, 0x56, 0x57, 0x53, 0x75, 0xf5, 0x34, 0x55, 0x8b, 0xdf, 0x1f, 0xd6, 0x9f, 0x04, 0xb2, 0xe7,
	0x38, 0xf8, 0x64, 0x05, 0x87, 0x02, 0xfd, 0xbc, 0x8d, 0xef, 0x1f, 0x18, 0xe1, 0xb3, 0x32, 0x17,
	0x3f, 0x25, 0xca, 0x20, 0xc3, 0x4e, 0x36, 0x7b, 0x54, 0x61, 0xd6, 0x99, 0x98, 0x28, 0xbd, 0x82,
	0x74, 0xc0, 0x6d, 0x8f, 0x2e, 0x4c, 0xca, 0xc5, 0x91, 0xd1, 0x4b, 0x98, 0x8d, 0xbd, 0x66, 0x8b,
	0x20, 0x7a, 0x78, 0x7a, 0x43, 0xfa, 0xcf, 0x1b, 0xe8, 0x3d, 0x2c, 0x47, 0xab, 0xa4, 0x43, 0x15,
	0x03, 0xb2, 0x3f, 0x03, 0x8a, 0xe8, 0x0f, 0xf6, 0x26, 0x0d, 0x86, 0xbb, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x19, 0x61, 0xc4, 0xd8, 0x01, 0x00, 0x00,
}
