// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/operator/operator.proto

package operator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operator struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName,json=first_name,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,json=last_name,proto3" json:"lastName,omitempty"`
	// Access ID and Access Token will be used for enhanced security,
	//  accessing the operator, etc
	Aid    string `protobuf:"bytes,3,opt,name=aid,json=access_id,proto3" json:"aid,omitempty"`
	Atoken string `protobuf:"bytes,6,opt,name=atoken,json=access_token,proto3" json:"atoken,omitempty"`
	// Unique identifier
	Uid string `protobuf:"bytes,4,opt,name=uid,json=id,proto3" json:"uid,omitempty"`
	// URI to an avatar image, best results it should be 1:1 ratio
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_operator_d148b4eafdb2c445, []int{0}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (dst *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(dst, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Operator) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Operator) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *Operator) GetAtoken() string {
	if m != nil {
		return m.Atoken
	}
	return ""
}

func (m *Operator) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Operator) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*Operator)(nil), "operator.Operator")
}

func init() {
	proto.RegisterFile("pkg/api/operator/operator.proto", fileDescriptor_operator_d148b4eafdb2c445)
}

var fileDescriptor_operator_d148b4eafdb2c445 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0x41, 0xaa, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xda, 0xbe, 0x17, 0xda, 0x41, 0x10, 0xb2, 0x28, 0x01, 0x15, 0xc5, 0x95, 0x2b,
	0xbb, 0xf0, 0x1e, 0x0a, 0x5e, 0xa0, 0x8c, 0x4d, 0x94, 0xa1, 0xb6, 0x09, 0x49, 0xf4, 0x46, 0xde,
	0x53, 0x9c, 0x46, 0x77, 0xf3, 0xfd, 0x7f, 0x9b, 0x81, 0xb5, 0xeb, 0x6f, 0x0d, 0x3a, 0x6a, 0xac,
	0x33, 0x1e, 0xa3, 0xf5, 0xbf, 0x63, 0xef, 0xbc, 0x8d, 0x56, 0x96, 0xdf, 0xbd, 0x7d, 0x65, 0x50,
	0x9e, 0xd2, 0x90, 0x2b, 0xa8, 0xae, 0xe4, 0x43, 0x3c, 0xe2, 0x60, 0x54, 0xb6, 0xc9, 0x76, 0xd5,
	0x19, 0x38, 0xb4, 0x23, 0x0e, 0x46, 0x2e, 0xa0, 0xbc, 0x63, 0xd2, 0x9c, 0xb5, 0xfa, 0xec, 0x09,
	0x6b, 0x28, 0x90, 0xb4, 0x2a, 0xa6, 0x8e, 0x5d, 0x67, 0x42, 0x68, 0x49, 0xcb, 0x25, 0x08, 0x8c,
	0xb6, 0x37, 0xa3, 0x12, 0x4c, 0xb3, 0x44, 0xdc, 0xe4, 0x1c, 0x8a, 0x07, 0x69, 0xf5, 0xc7, 0x94,
	0x93, 0x96, 0x35, 0x08, 0x7c, 0x62, 0x44, 0xaf, 0xfe, 0xb9, 0xa5, 0x75, 0x11, 0xfc, 0xf8, 0xe1,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x58, 0x75, 0x63, 0xdb, 0x00, 0x00, 0x00,
}
