// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operator/operator.proto

package operator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operator struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,json=first_name,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,json=last_name,proto3" json:"lastName,omitempty"`
	Aid                  string   `protobuf:"bytes,3,opt,name=aid,json=access_id,proto3" json:"aid,omitempty"`
	Atoken               string   `protobuf:"bytes,6,opt,name=atoken,json=access_token,proto3" json:"atoken,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,json=id,proto3" json:"uid,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_operator_af4a534969b54739, []int{0}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (dst *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(dst, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Operator) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Operator) GetAid() string {
	if m != nil {
		return m.Aid
	}
	return ""
}

func (m *Operator) GetAtoken() string {
	if m != nil {
		return m.Atoken
	}
	return ""
}

func (m *Operator) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Operator) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*Operator)(nil), "operator.Operator")
}

func init() { proto.RegisterFile("operator/operator.proto", fileDescriptor_operator_af4a534969b54739) }

var fileDescriptor_operator_af4a534969b54739 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x85, 0x61, 0xda, 0x6a, 0x48, 0x06, 0x41, 0x98, 0x45, 0x0d, 0xa8, 0x20, 0xae, 0x5c, 0xe9,
	0xc2, 0x7b, 0x28, 0x78, 0x81, 0x32, 0x36, 0x11, 0x82, 0xb6, 0x29, 0x49, 0xf4, 0x46, 0xde, 0x53,
	0x9c, 0xa6, 0xbb, 0x79, 0xff, 0xb7, 0x19, 0x58, 0xf9, 0xc1, 0x06, 0x4a, 0x3e, 0x9c, 0xa6, 0xe3,
	0x38, 0x04, 0x9f, 0x3c, 0xca, 0x69, 0xef, 0xbf, 0x05, 0xc8, 0x6b, 0x1e, 0xb8, 0x05, 0xf5, 0x70,
	0x21, 0xa6, 0x0b, 0x75, 0x56, 0x17, 0xbb, 0xe2, 0xa0, 0x6e, 0xc0, 0xa1, 0xe9, 0xa9, 0xb3, 0xb8,
	0x06, 0xf9, 0xa2, 0xac, 0x25, 0xab, 0xfa, 0xef, 0x11, 0x6b, 0xa8, 0xc8, 0x19, 0x5d, 0x8d, 0x9d,
	0xda, 0xd6, 0xc6, 0xd8, 0x38, 0x83, 0x1b, 0x10, 0x94, 0xfc, 0xd3, 0xf6, 0x5a, 0x30, 0x2d, 0x32,
	0x71, 0xc3, 0x25, 0x54, 0x6f, 0x67, 0xf4, 0x8c, 0xa9, 0x74, 0x06, 0x6b, 0x10, 0xf4, 0xa1, 0x44,
	0x41, 0xcf, 0xb9, 0xe5, 0x75, 0x17, 0xfc, 0xf8, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xca, 0x4f,
	0x99, 0x31, 0xd3, 0x00, 0x00, 0x00,
}
